package com.fuad.enums;

public enum OsAction {
    OPEN_APPLICATION,
    CLOSE_APPLICATION,
    FOCUS_APPLICATION,
    LIST_APPLICATIONS,
    LIST_RUNNING_APPLICATIONS,
    CHECK_APPLICATION_INSTALLED,
    GET_APPLICATION_STATUS,
    UNSUPPORTED
}
